# Generated by Django 3.2.7 on 2021-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=254)),
                ('project_description', models.TextField(max_length=500)),
                ('technologies_used', models.CharField(max_length=254)),
                ('project_image', models.ImageField(upload_to='')),
                ('live_site', models.GenericIPAddressField()),
            ],
        ),
    ]
