# Generated by Django 3.2.7 on 2021-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=254)),
                ('project_intro', models.CharField(default='This is a project                                      completed by Ger Tobin', max_length=254)),
                ('project_description', models.TextField(max_length=1000)),
                ('technologies_used', models.CharField(max_length=254)),
                ('project_image', models.ImageField(upload_to='')),
                ('git_hub_repo', models.CharField(default='https://github.com/Gertobin112', max_length=254)),
                ('live_site', models.CharField(max_length=254)),
            ],
        ),
    ]
