# Generated by Django 3.2.7 on 2021-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='project_date',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
