# Generated by Django 3.2.7 on 2021-10-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='live_site',
            field=models.CharField(max_length=254),
        ),
    ]
